            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Расписание</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
<?php if ($params['msg']): ?>
	<?php foreach($params['msg']['success'] as $msg): ?>
        <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <?php echo $msg; ?>            
        </div>
	<?php endforeach; ?>
<?php endif; ?>			
<div style="margin-bottom: 15px">
    <a href="/dashboard/add"><button type="button" class="btn btn-primary" >Записаться</button></a>
</div>
    <?php foreach ($params['course'] as $course): ?>
          <!--  <div class="row">-->
                <h3><?php echo $course->getName(); ?></h3>
                <?php foreach ($params['days'] as $d => $day): ?>
                <?php if ((($d -1) % 3) == 0): ?><div class="row"><?php endif ?>
                <div class="col-lg-4">
                            <div><?php echo $day; ?></div>
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline">
                                    <thead>
                                        <tr>
                                            <th style="width: 10%">Время</th>
                                            <th>Учитель</th>
                                            <th>Ученик</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($params['time_list'] as $t): ?>
                                        <tr>
                                            <td style="vertical-align: middle"><?php echo $t->format('H:i'); ?></td>
                                            <td style="vertical-align: middle"><?php if ($params['data'][$course->getId()][$d][$t->format('H:i')] ?? null): ?><?php echo $params['data'][$course->getId()][$d][$t->format('H:i')]->getTeacher()->getFullName(); ?><?php endif; ?></td>
                                            <td style="vertical-align: middle"><?php if ($params['data'][$course->getId()][$d][$t->format('H:i')] ?? null): ?><?php echo $params['data'][$course->getId()][$d][$t->format('H:i')]->getStudent()->getFullName(); ?><?php endif; ?></td>
                                        </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>

                    </div>
                </div>
                <?php if (($d % 3) == 0): ?></div><?php endif ?>
                <?php endforeach; ?>
                <?php if (($d % 3) != 0): ?></div><?php endif ?>
           <!-- </div>-->
    <?php endforeach; ?>

